### ISSUE TITLE
drone cluster

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [wesbos/javascript-drones#18]
Is it possible to drive multiple drone in same time as a cluster?

**Comment by wesbos** [comment]
Not easily. Each drone makes it's own wifi hotspot, so you'd need multiple wifi cards in your computer and then some way to aggregate that data

**Comment by ROBERT-MCDOWELL** [comment]
ok gotcha, an idea, create a multicast network (need a wifi router), and use the multicast ip to send the JS command to all. can work if, of course, each drone is a user part of the same network and not a hotspot.
