### ISSUE TITLE
Drone lands itself after a few seconds without command

### ISSUE THREAD

**Issue by seal62** [wesbos/javascript-drones#6]
Im finding my drone will land itself and start flashing red light (even when battery is 100%) after a few seconds of being in the air without a command. It will ignore any further commands until it has landed but is still sending through status updates. Is anybody else finding this?

**Comment by wesbos** [comment]
Yeah this is a safety feature. I bet you can just run battery? To get around this

**Comment by seal62** [comment]
Ah I had a feeling that might be the case and was wondering if that would be an easy fix for it. Ill give it a go. Thanks for the super fast response Wes, love the vid and code btw.
